name: "Genshin Impact Helper"

on:
  workflow_dispatch:
  schedule:
    - cron: "33 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: run sign
        run: |
          pip install -r requirements.txt
          echo "${{ secrets.COOKIE }}" | tr '#' "\n" | xargs -I {} sh -c 'echo "{}" | python3 ./genshin.py'

